# Travis CI configuration file
language: c++
compiler:
    - clang
    - gcc
sudo: required
dist: trusty
before_install:
    # Download and install G++5 if we're compiling for gcc, Clang-3.7 if we're compiling for clang
    - if (( "$CC" == "gcc" && "$CXX" == "g++" ))
    - then
    -   sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    -   sudo apt-get update -q
    -   sudo apt-get install gcc-5 -y
    -   sudo apt-get install g++-5 -y
    -   export CC=gcc-5
    -   export CXX=g++-5
    - elif (( "$CC" == "clang" && "$CXX" == "clang++" ))
    - then
    -   sudo add-apt-repository llvm-toolchain-trusty -y
    -   sudo apt-get update -q
    -   sudo apt-get install clang-3.7
    -   export CC=clang-3.7
    -   export CXX=clang++-3.7
    - else
    -   echo "Unknown compiler configuration"
    -   exit 1
    - fi
install:
    # Download engine dependencies
    - sudo apt-get install -y -qq libfreeimage-dev libpugixml-dev libglew-dev libbullet-dev
    # Download and compile GLFW, since it's not available in a Ubuntu repository on 14.04
    - sudo apt-get install -y -qq xorg-dev libglu1-mesa-dev
    - wget https://github.com/glfw/glfw/archive/3.1.2.tar.gz
    - tar -xzvf 3.1.2.tar.gz
    - cd glfw-3.1.2 && cmake -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF ./ && make && sudo make install && cd ../
script: 
    - mkdir build && cd build
    - cmake ../
    - make
