# Travis CI configuration file
language: c++
compiler:
    - clang
    - gcc
sudo: required
dist: trusty
install:
    - source ./travis-packages.sh
script: 
    - mkdir build && cd build
    - cmake ../
    - make
