# Travis CI configuration file
language: c++
compiler:
    - gcc
#   - clang TODO: Figure out why Clang A) Uses GCC's headers and B) errors out on them
sudo: required
dist: trusty
install:
    # Set up dependencies
    - ./CI/travis-packages.sh
    # Set compilers to latest version
    - if [ "$CC" == "gcc" ]; then export CC=gcc-5 && export CXX=g++-5; fi
    - if [ "$CC" == "clang" ]; then export CC=clang-3.7 && export CXX=clang++-3.7; fi
script: 
    - mkdir build && cd build
    - cmake ../
    - make
