# AppVeyor CI configuration file
version: '0.0.{build}'
os: Visual Studio 2015
configuration: 
  - Release
  - Debug
platform: 
  - x64
  - Win32
install:
  cmd: C:\Python35-x64\python.exe packages.py
build:
  project: WillowEngine.sln
  parallel: true
  verbosity: minimal
artifacts:
  path: bin
  name: 'Willow Engine $(APPVEYOR_BUILD_VERSION) $(PLATFORM) $(CONFIGURATION)'
  