# AppVeyor CI configuration file
version: '0.0.{build}'
os: Visual Studio 2015
configuration: 
  - Release
  - Debug
platform: 
  - x64
  - Win32
install:
  cmd: setx PATH "C:\Python35-x64\;%PATH%"
build:
  project: WillowEngine.sln
  parallel: true
  verbosity: minimal
artifacts:
  path: bin\$(PLATFORM)\$(CONFIGURATION)
  name: 'Willow Engine $(APPVEYOR_BUILD_VERSION) $(PLATFORM) $(CONFIGURATION)'
  