# AppVeyor CI configuration file
version: '{build}'
os: Visual Studio 2015
configuration: 
  - Release
  - Debug
platform: 
  - x64
  - Win32
install:
  cmd: C:\Python35-x64\python.exe packages.py
build:
  project: WillowEngine.sln
  parallel: true
  verbosity: normal
artifacts:
  path: bin
  